language: java
env:
  global:
  - GITHUB_REPO=symbiote-h2020/EnablerPlatformProxy
  - secure: QTpMZAw/rq24i/8mb99iAI+7YhYP0G1TFlNwlbHNzzDD9N/0b4tCWd8pxEJ7jn3bPX6xoMwMUaxhtwA9Ph3k4h7k7k2q5d7vonTf6AU0NfBkCw5a1ODYMxZuBPu8wdJ0oFwCyoWtpzLxWBth3//vtFlcYENuoXBwz9nXi1f5mrv0Iae8Cp2dKk1WZ3946JNEK1LSGn54vLdgtY/TkKX194+fSR7SpnrXJ901Hd/+EM7LctKNFLFyOzlQD838aXGFARM5pgoC/2t9PUwbbtttk783IDs3nUd9jpdWTez23SXvJMhtbRx8ZCGnv1LtImssjNOlmLg/92pQg5F33oQd+MXXhDv38SKKx8fMpA0kJPJdWCzkKhZNz3/mFtMiWQHoPoQFHFv3opVfkwOLZpdOcJDPKgQdLchtFeaFWIkduLUf0JvcvyxyhP2rvLw5fzThuj8UxSAhPaUq6gU9P7rLIwkf7/KhKm62fMtq3aChu6QWWXKprkZfIfdAH+fMeUX+iRYGpP9EpiG7zhJ5yQVIWtfbquZ5/xHaFfdhGzMXxRQzUV/ZeDp2b28E0S/oHEjnAUD+0hLxWnORgHgrZ5V58+Xoxp1hSPqPk7Lu/Jnk9MDlCuNPYBjwWxSkRasm3dPcvXBhLlt3X/oxBQpric4Oeb+undKPXR5BxZR24lK3ivs=
jdk:
- oraclejdk8
services:
- mongodb
- rabbitmq
sudo: required
branches:
  only:
  - staging
install: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_script:
- chmod a+x merge_script.sh
- "./merge_script.sh"
after_success:
- chmod a+x pushing_script.sh
- "./pushing_script.sh"
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: always
